# Generated by Django 3.0.8 on 2021-05-03 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20210504_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communities',
            name='post_id',
        ),
    ]
