# Generated by Django 3.0.8 on 2021-05-12 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0005_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='slug',
            field=models.SlugField(default='lol', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
